// 30 個 AI Coach 預設場景

import type { CoachScenarioConfig, CoachScenario } from '../types'

export const COACH_SCENARIOS: CoachScenarioConfig[] = [
  // --- Objection Handling (10 scenarios) ---
  {
    id: 'cold_call',
    name: {
      'en': 'Cold Call', 'zh-TW': '陌生開發電話', 'zh-CN': '陌生开发电话',
      'ja': 'コールドコール', 'ko': '콜드콜',
      'th': 'โทรหาลูกค้าใหม่', 'vi': 'Gọi điện lạnh', 'ms': 'Panggilan Dingin', 'id': 'Panggilan Dingin',
    },
    description: {
      'en': 'Practice making an unsolicited call to a prospect who doesn\'t know you.',
      'zh-TW': '練習打電話給不認識你的潛在客戶。', 'zh-CN': '练习打电话给不认识你的潜在客户。',
      'ja': 'あなたを知らない見込み客への電話を練習します。', 'ko': '당신을 모르는 잠재 고객에게 전화하는 연습입니다.',
      'th': 'ฝึกโทรหาลูกค้าที่ไม่รู้จักคุณ', 'vi': 'Luyện tập gọi điện cho khách hàng tiềm năng chưa biết bạn.',
      'ms': 'Berlatih membuat panggilan kepada prospek yang tidak mengenali anda.', 'id': 'Berlatih menelepon prospek yang tidak mengenal Anda.',
    },
    difficulty: 'intermediate',
    category: 'discovery',
    aiRole: 'Busy professional receiving an unexpected sales call',
    aiPersonality: 'Slightly impatient but professional. Will give 30 seconds of attention.',
    expectedSkills: ['attention grabbing', 'quick value proposition', 'permission-based selling'],
    maxTurns: 8,
  },
  {
    id: 'objection_price',
    name: {
      'en': 'Price Objection', 'zh-TW': '價格異議', 'zh-CN': '价格异议',
      'ja': '価格の異議', 'ko': '가격 이의',
      'th': 'ข้อโต้แย้งเรื่องราคา', 'vi': 'Phản đối về giá', 'ms': 'Bantahan Harga', 'id': 'Keberatan Harga',
    },
    description: {
      'en': 'Handle a client who thinks your product is too expensive.',
      'zh-TW': '處理客戶認為產品太貴的異議。', 'zh-CN': '处理客户认为产品太贵的异议。',
      'ja': '製品が高すぎると感じている顧客の対応を練習します。', 'ko': '제품이 너무 비싸다고 생각하는 고객을 대응하는 연습입니다.',
      'th': 'จัดการกับลูกค้าที่คิดว่าสินค้าแพงเกินไป', 'vi': 'Xử lý khách hàng cho rằng sản phẩm quá đắt.',
      'ms': 'Tangani pelanggan yang merasakan produk anda terlalu mahal.', 'id': 'Tangani klien yang merasa produk Anda terlalu mahal.',
    },
    difficulty: 'intermediate',
    category: 'objection',
    aiRole: 'Interested buyer with budget concerns',
    aiPersonality: 'Firm on budget but reasonable. Responds to value arguments.',
    expectedSkills: ['value framing', 'ROI calculation', 'price anchoring'],
    maxTurns: 10,
  },
  {
    id: 'objection_timing',
    name: {
      'en': 'Timing Objection', 'zh-TW': '時機異議', 'zh-CN': '时机异议',
      'ja': 'タイミングの異議', 'ko': '시기 이의',
      'th': 'ข้อโต้แย้งเรื่องเวลา', 'vi': 'Phản đối về thời điểm', 'ms': 'Bantahan Masa', 'id': 'Keberatan Waktu',
    },
    description: {
      'en': 'Deal with "not the right time" objection.', 'zh-TW': '處理「現在不是好時機」的異議。', 'zh-CN': '处理"现在不是好时机"的异议。',
      'ja': '「今はタイミングが悪い」という異議に対処します。', 'ko': '"지금은 적절한 시기가 아닙니다"라는 반대에 대처합니다.',
      'th': 'จัดการกับ "ตอนนี้ไม่ใช่เวลาที่เหมาะ"', 'vi': 'Xử lý phản đối "chưa phải lúc".',
      'ms': 'Tangani bantahan "bukan masa yang sesuai".', 'id': 'Tangani keberatan "bukan waktu yang tepat".',
    },
    difficulty: 'intermediate',
    category: 'objection',
    aiRole: 'Decision maker with quarterly budget constraints',
    aiPersonality: 'Genuinely interested but constrained by timing.',
    expectedSkills: ['urgency creation', 'cost of delay', 'pilot proposal'],
    maxTurns: 8,
  },
  {
    id: 'objection_competitor',
    name: {
      'en': 'Competitor Objection', 'zh-TW': '競爭對手異議', 'zh-CN': '竞争对手异议',
      'ja': '競合の異議', 'ko': '경쟁사 이의',
      'th': 'ข้อโต้แย้งเรื่องคู่แข่ง', 'vi': 'Phản đối về đối thủ', 'ms': 'Bantahan Pesaing', 'id': 'Keberatan Kompetitor',
    },
    description: {
      'en': 'Win over a client already using a competitor.', 'zh-TW': '贏得已經在使用競爭對手產品的客戶。', 'zh-CN': '赢得已经在使用竞争对手产品的客户。',
      'ja': '競合製品を使用中の顧客を獲得する練習です。', 'ko': '이미 경쟁사 제품을 사용하고 있는 고객을 설득하는 연습입니다.',
      'th': 'ชนะใจลูกค้าที่ใช้คู่แข่งอยู่แล้ว', 'vi': 'Thuyết phục khách hàng đang dùng sản phẩm đối thủ.',
      'ms': 'Memenangi pelanggan yang sudah menggunakan pesaing.', 'id': 'Memenangkan klien yang sudah menggunakan kompetitor.',
    },
    difficulty: 'advanced',
    category: 'objection',
    aiRole: 'Loyal user of a competing product',
    aiPersonality: 'Satisfied with current solution but open to hearing alternatives.',
    expectedSkills: ['competitive differentiation', 'migration value', 'risk mitigation'],
    maxTurns: 10,
  },
  {
    id: 'objection_no_budget',
    name: {
      'en': 'No Budget', 'zh-TW': '沒有預算', 'zh-CN': '没有预算',
      'ja': '予算なし', 'ko': '예산 없음',
      'th': 'ไม่มีงบประมาณ', 'vi': 'Không có ngân sách', 'ms': 'Tiada Bajet', 'id': 'Tidak Ada Anggaran',
    },
    description: {
      'en': 'Handle a genuine budget constraint creatively.', 'zh-TW': '創造性地處理真正的預算限制。', 'zh-CN': '创造性地处理真正的预算限制。',
      'ja': '本当の予算制約に創造的に対処します。', 'ko': '실제 예산 제약을 창의적으로 처리합니다.',
      'th': 'จัดการข้อจำกัดด้านงบประมาณอย่างสร้างสรรค์', 'vi': 'Xử lý sáng tạo hạn chế ngân sách thực sự.',
      'ms': 'Tangani kekangan bajet sebenar secara kreatif.', 'id': 'Tangani keterbatasan anggaran secara kreatif.',
    },
    difficulty: 'advanced',
    category: 'objection',
    aiRole: 'Manager who genuinely has no budget allocation',
    aiPersonality: 'Honest and transparent about constraints.',
    expectedSkills: ['creative financing', 'phased rollout', 'ROI business case'],
    maxTurns: 8,
  },
  {
    id: 'objection_need_approval',
    name: {
      'en': 'Need Approval', 'zh-TW': '需要上級批准', 'zh-CN': '需要上级批准',
      'ja': '承認が必要', 'ko': '승인 필요',
      'th': 'ต้องได้รับอนุมัติ', 'vi': 'Cần phê duyệt', 'ms': 'Perlu Kelulusan', 'id': 'Perlu Persetujuan',
    },
    description: {
      'en': 'Navigate multi-level decision making.', 'zh-TW': '應對多層級決策流程。', 'zh-CN': '应对多层级决策流程。',
      'ja': '多層の意思決定プロセスに対応します。', 'ko': '다단계 의사 결정을 탐색합니다.',
      'th': 'จัดการกับการตัดสินใจหลายระดับ', 'vi': 'Điều hướng quy trình ra quyết định nhiều cấp.',
      'ms': 'Navigasi membuat keputusan pelbagai peringkat.', 'id': 'Navigasi pengambilan keputusan multi-level.',
    },
    difficulty: 'intermediate',
    category: 'objection',
    aiRole: 'Champion who needs boss\'s sign-off',
    aiPersonality: 'Supportive but cautious about internal politics.',
    expectedSkills: ['champion enablement', 'executive summary', 'stakeholder mapping'],
    maxTurns: 8,
  },
  {
    id: 'objection_already_have',
    name: {
      'en': 'Already Have Solution', 'zh-TW': '已有解決方案', 'zh-CN': '已有解决方案',
      'ja': '既存ソリューションあり', 'ko': '이미 솔루션 보유',
      'th': 'มีโซลูชันอยู่แล้ว', 'vi': 'Đã có giải pháp', 'ms': 'Sudah Ada Penyelesaian', 'id': 'Sudah Punya Solusi',
    },
    description: {
      'en': 'Differentiate from an existing solution the client uses.', 'zh-TW': '與客戶現有方案做出差異化。', 'zh-CN': '与客户现有方案做出差异化。',
      'ja': '顧客が使用している既存ソリューションとの差別化。', 'ko': '고객이 사용 중인 기존 솔루션과 차별화합니다.',
      'th': 'สร้างความแตกต่างจากโซลูชันที่มีอยู่', 'vi': 'Tạo sự khác biệt với giải pháp hiện có.',
      'ms': 'Bezakan daripada penyelesaian sedia ada.', 'id': 'Bedakan dari solusi yang sudah ada.',
    },
    difficulty: 'intermediate',
    category: 'objection',
    aiRole: 'User with an existing but imperfect solution',
    aiPersonality: 'Comfortable with status quo, not looking to change.',
    expectedSkills: ['gap analysis', 'switching value', 'migration support'],
    maxTurns: 8,
  },
  {
    id: 'objection_too_complex',
    name: {
      'en': 'Too Complex', 'zh-TW': '太複雜', 'zh-CN': '太复杂',
      'ja': '複雑すぎる', 'ko': '너무 복잡함',
      'th': 'ซับซ้อนเกินไป', 'vi': 'Quá phức tạp', 'ms': 'Terlalu Kompleks', 'id': 'Terlalu Rumit',
    },
    description: {
      'en': 'Address implementation complexity concerns.', 'zh-TW': '處理客戶對導入複雜度的擔憂。', 'zh-CN': '处理客户对导入复杂度的担忧。',
      'ja': '導入の複雑さに関する懸念に対処します。', 'ko': '구현 복잡성에 대한 우려를 해결합니다.',
      'th': 'จัดการความกังวลเรื่องความซับซ้อนในการนำไปใช้', 'vi': 'Giải quyết lo ngại về độ phức tạp triển khai.',
      'ms': 'Tangani kebimbangan kerumitan pelaksanaan.', 'id': 'Atasi kekhawatiran kompleksitas implementasi.',
    },
    difficulty: 'intermediate',
    category: 'objection',
    aiRole: 'IT manager worried about team adoption',
    aiPersonality: 'Technically savvy, risk-averse.',
    expectedSkills: ['simplification', 'onboarding plan', 'success stories'],
    maxTurns: 8,
  },
  {
    id: 'objection_not_interested',
    name: {
      'en': 'Not Interested', 'zh-TW': '沒有興趣', 'zh-CN': '没有兴趣',
      'ja': '興味なし', 'ko': '관심 없음',
      'th': 'ไม่สนใจ', 'vi': 'Không quan tâm', 'ms': 'Tidak Berminat', 'id': 'Tidak Tertarik',
    },
    description: {
      'en': 'Turn around a flat "not interested" response.', 'zh-TW': '扭轉客戶直接說「沒興趣」的情況。', 'zh-CN': '扭转客户直接说"没兴趣"的情况。',
      'ja': '「興味ありません」という反応を覆す練習。', 'ko': '"관심 없습니다"라는 반응을 뒤집는 연습입니다.',
      'th': 'พลิกสถานการณ์จาก "ไม่สนใจ"', 'vi': 'Xoay chuyển phản hồi "không quan tâm".',
      'ms': 'Pusingkan respons "tidak berminat".', 'id': 'Balikkan respons "tidak tertarik".',
    },
    difficulty: 'advanced',
    category: 'objection',
    aiRole: 'Busy professional who dismisses sales calls',
    aiPersonality: 'Polite but firm. Only reconsiders for genuinely relevant insight.',
    expectedSkills: ['pattern interrupt', 'insight selling', 'value hook'],
    maxTurns: 6,
  },
  {
    id: 'objection_send_info',
    name: {
      'en': 'Just Send Info', 'zh-TW': '先寄資料', 'zh-CN': '先发资料',
      'ja': '資料を送ってください', 'ko': '자료 보내주세요',
      'th': 'ส่งข้อมูลมาก่อน', 'vi': 'Gửi tài liệu trước', 'ms': 'Hantar Maklumat Sahaja', 'id': 'Kirim Informasi Saja',
    },
    description: {
      'en': 'Handle the polite brush-off of "just send me some info".', 'zh-TW': '處理客戶用「先寄資料」來婉拒的情況。', 'zh-CN': '处理客户用"先发资料"来婉拒的情况。',
      'ja': '「資料を送ってください」という丁寧な断りに対処します。', 'ko': '"자료만 보내주세요"라는 정중한 거절에 대처합니다.',
      'th': 'จัดการกับ "ส่งข้อมูลมาก่อน" ที่เป็นการปฏิเสธอย่างสุภาพ', 'vi': 'Xử lý cách từ chối lịch sự "gửi tài liệu trước".',
      'ms': 'Tangani penolakan sopan "hantar maklumat sahaja".', 'id': 'Tangani penolakan halus "kirim informasi saja".',
    },
    difficulty: 'intermediate',
    category: 'objection',
    aiRole: 'Person trying to end the conversation politely',
    aiPersonality: 'Not rude, just busy and using a common deflection.',
    expectedSkills: ['re-engagement', 'qualifying questions', 'micro-commitment'],
    maxTurns: 6,
  },

  // --- Discovery (2 scenarios) ---
  {
    id: 'needs_discovery',
    name: {
      'en': 'Needs Discovery', 'zh-TW': '需求探索', 'zh-CN': '需求探索',
      'ja': 'ニーズ発見', 'ko': '니즈 발견',
      'th': 'การค้นหาความต้องการ', 'vi': 'Khám phá nhu cầu', 'ms': 'Penemuan Keperluan', 'id': 'Penemuan Kebutuhan',
    },
    description: {
      'en': 'Uncover a client\'s real needs through skilled questioning.', 'zh-TW': '透過提問技巧挖掘客戶真正的需求。', 'zh-CN': '通过提问技巧挖掘客户真正的需求。',
      'ja': '巧みな質問で顧客の本当のニーズを発見します。', 'ko': '숙련된 질문으로 고객의 실제 니즈를 발견합니다.',
      'th': 'ค้นหาความต้องการที่แท้จริงของลูกค้า', 'vi': 'Khám phá nhu cầu thực sự của khách hàng.',
      'ms': 'Temui keperluan sebenar pelanggan.', 'id': 'Temukan kebutuhan nyata klien.',
    },
    difficulty: 'beginner',
    category: 'discovery',
    aiRole: 'Client with problems but unsure what solution they need',
    aiPersonality: 'Open and willing to share, responds well to genuine curiosity.',
    expectedSkills: ['open questions', 'active listening', 'pain point identification'],
    maxTurns: 10,
  },
  {
    id: 'needs_deep_dive',
    name: {
      'en': 'Deep Dive Discovery', 'zh-TW': '深度需求探索', 'zh-CN': '深度需求探索',
      'ja': 'ディープダイブ', 'ko': '심층 발견',
      'th': 'การค้นหาเชิงลึก', 'vi': 'Khám phá chuyên sâu', 'ms': 'Penemuan Mendalam', 'id': 'Penemuan Mendalam',
    },
    description: {
      'en': 'Go deep into a client\'s specific technical challenges.', 'zh-TW': '深入了解客戶的具體技術挑戰。', 'zh-CN': '深入了解客户的具体技术挑战。',
      'ja': '顧客の具体的な技術課題を深掘りします。', 'ko': '고객의 구체적인 기술 과제를 깊이 탐구합니다.',
      'th': 'เจาะลึกความท้าทายเฉพาะของลูกค้า', 'vi': 'Đi sâu vào thách thức kỹ thuật cụ thể.',
      'ms': 'Selami cabaran teknikal khusus pelanggan.', 'id': 'Dalami tantangan teknis spesifik klien.',
    },
    difficulty: 'advanced',
    category: 'discovery',
    aiRole: 'Technical lead with a specific workflow problem',
    aiPersonality: 'Detail-oriented, expects the salesperson to understand their domain.',
    expectedSkills: ['technical empathy', 'consultative questioning', 'solution mapping'],
    maxTurns: 12,
  },

  // --- Closing (4 scenarios) ---
  {
    id: 'closing_assumptive',
    name: {
      'en': 'Assumptive Close', 'zh-TW': '假設成交', 'zh-CN': '假设成交',
      'ja': '仮定クロージング', 'ko': '가정 클로징',
      'th': 'การปิดแบบสันนิษฐาน', 'vi': 'Chốt giả định', 'ms': 'Penutupan Andaian', 'id': 'Penutupan Asumsi',
    },
    description: {
      'en': 'Practice the assumptive close technique.', 'zh-TW': '練習假設成交技巧。', 'zh-CN': '练习假设成交技巧。',
      'ja': '仮定クロージングテクニックを練習します。', 'ko': '가정 클로징 기법을 연습합니다.',
      'th': 'ฝึกเทคนิคการปิดแบบสันนิษฐาน', 'vi': 'Luyện kỹ thuật chốt giả định.',
      'ms': 'Berlatih teknik penutupan andaian.', 'id': 'Berlatih teknik penutupan asumsi.',
    },
    difficulty: 'intermediate',
    category: 'closing',
    aiRole: 'Prospect who is 80% convinced',
    aiPersonality: 'Leaning yes but needs the final push. Not pushy-resistant.',
    expectedSkills: ['confidence', 'natural transition', 'next steps'],
    maxTurns: 6,
  },
  {
    id: 'closing_urgency',
    name: {
      'en': 'Urgency Close', 'zh-TW': '緊迫感成交', 'zh-CN': '紧迫感成交',
      'ja': '緊急性クロージング', 'ko': '긴급성 클로징',
      'th': 'การปิดแบบเร่งด่วน', 'vi': 'Chốt khẩn cấp', 'ms': 'Penutupan Segera', 'id': 'Penutupan Urgensi',
    },
    description: {
      'en': 'Create legitimate urgency without being manipulative.', 'zh-TW': '建立正當的緊迫感而不顯得操控。', 'zh-CN': '建立正当的紧迫感而不显得操控。',
      'ja': '操作的にならずに正当な緊急性を作ります。', 'ko': '조작적이지 않으면서 합당한 긴급성을 만듭니다.',
      'th': 'สร้างความเร่งด่วนที่ถูกต้องโดยไม่บิดเบือน', 'vi': 'Tạo tính khẩn cấp chính đáng.',
      'ms': 'Wujudkan kesegeraan yang sah.', 'id': 'Ciptakan urgensi yang sah.',
    },
    difficulty: 'intermediate',
    category: 'closing',
    aiRole: 'Interested but procrastinating buyer',
    aiPersonality: 'Agrees the product is good but sees no rush.',
    expectedSkills: ['legitimate urgency', 'cost of delay', 'deadline setting'],
    maxTurns: 6,
  },
  {
    id: 'closing_summary',
    name: {
      'en': 'Summary Close', 'zh-TW': '摘要成交', 'zh-CN': '摘要成交',
      'ja': '要約クロージング', 'ko': '요약 클로징',
      'th': 'การปิดแบบสรุป', 'vi': 'Chốt tóm tắt', 'ms': 'Penutupan Ringkasan', 'id': 'Penutupan Rangkuman',
    },
    description: {
      'en': 'Summarize value and close after multiple meetings.', 'zh-TW': '在多次會議後總結價值並成交。', 'zh-CN': '在多次会议后总结价值并成交。',
      'ja': '複数回の会議後に価値をまとめてクロージングします。', 'ko': '여러 회의 후 가치를 요약하고 클로징합니다.',
      'th': 'สรุปคุณค่าและปิดหลังจากหลายการประชุม', 'vi': 'Tóm tắt giá trị và chốt sau nhiều cuộc họp.',
      'ms': 'Ringkaskan nilai dan tutup selepas pelbagai mesyuarat.', 'id': 'Rangkum nilai dan tutup setelah beberapa pertemuan.',
    },
    difficulty: 'advanced',
    category: 'closing',
    aiRole: 'Decision maker who needs final recap',
    aiPersonality: 'Analytical, wants to see all value points laid out clearly.',
    expectedSkills: ['value summary', 'benefit stacking', 'decision facilitation'],
    maxTurns: 8,
  },
  {
    id: 'closing_alternative',
    name: {
      'en': 'Alternative Close', 'zh-TW': '二擇一成交', 'zh-CN': '二选一成交',
      'ja': '二者択一クロージング', 'ko': '양자택일 클로징',
      'th': 'การปิดแบบทางเลือก', 'vi': 'Chốt lựa chọn', 'ms': 'Penutupan Alternatif', 'id': 'Penutupan Alternatif',
    },
    description: {
      'en': 'Help a client choose between options.', 'zh-TW': '幫助客戶在選項之間做出選擇。', 'zh-CN': '帮助客户在选项之间做出选择。',
      'ja': '顧客がオプション間で選択するのを助けます。', 'ko': '고객이 옵션 사이에서 선택하도록 돕습니다.',
      'th': 'ช่วยลูกค้าเลือกระหว่างตัวเลือก', 'vi': 'Giúp khách hàng chọn giữa các phương án.',
      'ms': 'Bantu pelanggan memilih antara pilihan.', 'id': 'Bantu klien memilih antara opsi.',
    },
    difficulty: 'beginner',
    category: 'closing',
    aiRole: 'Buyer torn between two options',
    aiPersonality: 'Indecisive but willing to be guided.',
    expectedSkills: ['consultative selling', 'option framing', 'gentle guidance'],
    maxTurns: 6,
  },

  // --- Presentation (2 scenarios) ---
  {
    id: 'presentation',
    name: {
      'en': 'Product Presentation', 'zh-TW': '產品簡報', 'zh-CN': '产品简报',
      'ja': '製品プレゼンテーション', 'ko': '제품 프레젠테이션',
      'th': 'การนำเสนอสินค้า', 'vi': 'Trình bày sản phẩm', 'ms': 'Pembentangan Produk', 'id': 'Presentasi Produk',
    },
    description: {
      'en': 'Present your product to a room of stakeholders.', 'zh-TW': '向一群利害關係人介紹你的產品。', 'zh-CN': '向一群利害关系人介绍你的产品。',
      'ja': 'ステークホルダーに製品をプレゼンテーションします。', 'ko': '이해관계자들에게 제품을 프레젠테이션합니다.',
      'th': 'นำเสนอผลิตภัณฑ์ต่อผู้มีส่วนได้ส่วนเสีย', 'vi': 'Trình bày sản phẩm cho các bên liên quan.',
      'ms': 'Bentangkan produk anda kepada pihak berkepentingan.', 'id': 'Presentasikan produk Anda kepada pemangku kepentingan.',
    },
    difficulty: 'intermediate',
    category: 'presentation',
    aiRole: 'Skeptical audience member who asks tough questions',
    aiPersonality: 'Analytical, challenges assumptions, wants proof.',
    expectedSkills: ['storytelling', 'data presentation', 'Q&A handling'],
    maxTurns: 10,
  },
  {
    id: 'presentation_demo',
    name: {
      'en': 'Product Demo', 'zh-TW': '產品展示', 'zh-CN': '产品演示',
      'ja': '製品デモ', 'ko': '제품 데모',
      'th': 'สาธิตสินค้า', 'vi': 'Demo sản phẩm', 'ms': 'Demo Produk', 'id': 'Demo Produk',
    },
    description: {
      'en': 'Walk a client through a product demo.', 'zh-TW': '帶客戶走過產品展示流程。', 'zh-CN': '带客户走过产品演示流程。',
      'ja': '製品デモを顧客に案内します。', 'ko': '고객에게 제품 데모를 진행합니다.',
      'th': 'พาลูกค้าดูการสาธิตสินค้า', 'vi': 'Hướng dẫn khách hàng qua demo sản phẩm.',
      'ms': 'Bawa pelanggan melalui demo produk.', 'id': 'Ajak klien melalui demo produk.',
    },
    difficulty: 'intermediate',
    category: 'presentation',
    aiRole: 'Evaluator comparing solutions',
    aiPersonality: 'Detail-oriented, takes notes, compares features.',
    expectedSkills: ['use case mapping', 'feature-benefit linking', 'handling comparisons'],
    maxTurns: 10,
  },

  // --- Follow-up (2 scenarios) ---
  {
    id: 'follow_up_call',
    name: {
      'en': 'Follow-up Call', 'zh-TW': '跟進電話', 'zh-CN': '跟进电话',
      'ja': 'フォローアップ電話', 'ko': '후속 전화',
      'th': 'โทรติดตาม', 'vi': 'Gọi theo dõi', 'ms': 'Panggilan Susulan', 'id': 'Panggilan Tindak Lanjut',
    },
    description: {
      'en': 'Follow up after a good initial meeting.', 'zh-TW': '在良好的初次會議後進行跟進。', 'zh-CN': '在良好的初次会议后进行跟进。',
      'ja': '良い初回会議後のフォローアップ。', 'ko': '좋은 초기 미팅 후 후속 연락.',
      'th': 'ติดตามหลังการประชุมครั้งแรกที่ดี', 'vi': 'Theo dõi sau cuộc họp đầu tiên tốt đẹp.',
      'ms': 'Susulan selepas mesyuarat pertama yang baik.', 'id': 'Tindak lanjut setelah pertemuan awal yang baik.',
    },
    difficulty: 'beginner',
    category: 'follow_up',
    aiRole: 'Client who had a positive first meeting',
    aiPersonality: 'Friendly, remembers the salesperson, but has been busy.',
    expectedSkills: ['relationship building', 'value recap', 'next steps'],
    maxTurns: 6,
  },
  {
    id: 'follow_up_no_response',
    name: {
      'en': 'No Response Follow-up', 'zh-TW': '沒有回應的跟進', 'zh-CN': '没有回应的跟进',
      'ja': '返信なしフォローアップ', 'ko': '무응답 후속',
      'th': 'ติดตามเมื่อไม่ได้รับการตอบกลับ', 'vi': 'Theo dõi khi không phản hồi', 'ms': 'Susulan Tanpa Maklum Balas', 'id': 'Tindak Lanjut Tanpa Respons',
    },
    description: {
      'en': 'Re-engage a prospect who stopped responding.', 'zh-TW': '重新聯繫不再回覆的潛在客戶。', 'zh-CN': '重新联系不再回复的潜在客户。',
      'ja': '返信が途絶えた見込み客に再アプローチ。', 'ko': '응답을 중단한 잠재 고객에게 재연락.',
      'th': 'ติดต่อลูกค้าที่หยุดตอบกลับอีกครั้ง', 'vi': 'Tái kết nối khách hàng ngưng phản hồi.',
      'ms': 'Libatkan semula prospek yang berhenti membalas.', 'id': 'Hubungi kembali prospek yang berhenti merespons.',
    },
    difficulty: 'intermediate',
    category: 'follow_up',
    aiRole: 'Prospect who ghosted after initial interest',
    aiPersonality: 'Not hostile, just deprioritized. Responds to new value.',
    expectedSkills: ['pattern interrupt', 'new value injection', 'low-pressure re-engagement'],
    maxTurns: 6,
  },

  // --- Referral (2 scenarios) ---
  {
    id: 'referral_ask',
    name: {
      'en': 'Ask for Referrals', 'zh-TW': '請求引薦', 'zh-CN': '请求引荐',
      'ja': '紹介依頼', 'ko': '소개 요청',
      'th': 'ขอการแนะนำ', 'vi': 'Xin giới thiệu', 'ms': 'Minta Rujukan', 'id': 'Minta Referensi',
    },
    description: {
      'en': 'Ask a satisfied customer for referrals.', 'zh-TW': '向滿意的客戶請求引薦。', 'zh-CN': '向满意的客户请求引荐。',
      'ja': '満足した顧客に紹介を依頼します。', 'ko': '만족한 고객에게 소개를 요청합니다.',
      'th': 'ขอการแนะนำจากลูกค้าที่พอใจ', 'vi': 'Xin giới thiệu từ khách hàng hài lòng.',
      'ms': 'Minta rujukan daripada pelanggan yang berpuas hati.', 'id': 'Minta referensi dari pelanggan yang puas.',
    },
    difficulty: 'beginner',
    category: 'networking',
    aiRole: 'Happy customer who is willing to help',
    aiPersonality: 'Supportive, likes the product, but has boundaries.',
    expectedSkills: ['relationship leverage', 'specific ask', 'making it easy'],
    maxTurns: 6,
  },
  {
    id: 'referral_introduction',
    name: {
      'en': 'Referral Introduction', 'zh-TW': '引薦介紹', 'zh-CN': '引荐介绍',
      'ja': '紹介入門', 'ko': '소개 도입',
      'th': 'การแนะนำจากผู้อ้างอิง', 'vi': 'Giới thiệu qua người quen', 'ms': 'Pengenalan Rujukan', 'id': 'Pengenalan Referensi',
    },
    description: {
      'en': 'Leverage a warm introduction from a mutual connection.', 'zh-TW': '利用共同關係人的溫暖介紹。', 'zh-CN': '利用共同关系人的温暖介绍。',
      'ja': '共通の知人からの紹介を活用します。', 'ko': '공통 인맥의 따뜻한 소개를 활용합니다.',
      'th': 'ใช้ประโยชน์จากการแนะนำจากคนรู้จักร่วม', 'vi': 'Tận dụng giới thiệu từ người quen chung.',
      'ms': 'Manfaatkan pengenalan hangat daripada kenalan bersama.', 'id': 'Manfaatkan perkenalan hangat dari koneksi bersama.',
    },
    difficulty: 'beginner',
    category: 'networking',
    aiRole: 'Person referred by a mutual contact',
    aiPersonality: 'Gives benefit of the doubt due to referral.',
    expectedSkills: ['trust transfer', 'credibility building', 'relevant value prop'],
    maxTurns: 8,
  },

  // --- Advanced Scenarios (6 scenarios) ---
  {
    id: 'upsell',
    name: {
      'en': 'Upsell', 'zh-TW': '向上銷售', 'zh-CN': '向上销售',
      'ja': 'アップセル', 'ko': '업셀',
      'th': 'อัพเซลล์', 'vi': 'Bán nâng cấp', 'ms': 'Jualan Naik', 'id': 'Upsell',
    },
    description: {
      'en': 'Upsell an existing customer to a higher tier.', 'zh-TW': '向現有客戶推薦升級方案。', 'zh-CN': '向现有客户推荐升级方案。',
      'ja': '既存顧客に上位プランをアップセルします。', 'ko': '기존 고객에게 상위 등급을 업셀합니다.',
      'th': 'อัพเซลล์ลูกค้าเดิมไปยังระดับที่สูงขึ้น', 'vi': 'Bán nâng cấp cho khách hàng hiện tại.',
      'ms': 'Jual naik pelanggan sedia ada ke peringkat lebih tinggi.', 'id': 'Upsell pelanggan yang ada ke tier lebih tinggi.',
    },
    difficulty: 'intermediate',
    category: 'closing',
    aiRole: 'Existing happy customer on basic plan',
    aiPersonality: 'Satisfied with current plan, cautiously curious about upgrades.',
    expectedSkills: ['value expansion', 'usage-based selling', 'seamless transition'],
    maxTurns: 8,
  },
  {
    id: 'cross_sell',
    name: {
      'en': 'Cross-Sell', 'zh-TW': '交叉銷售', 'zh-CN': '交叉销售',
      'ja': 'クロスセル', 'ko': '크로스셀',
      'th': 'ครอสเซลล์', 'vi': 'Bán chéo', 'ms': 'Jualan Silang', 'id': 'Cross-Sell',
    },
    description: {
      'en': 'Introduce a complementary product to an existing customer.', 'zh-TW': '向現有客戶介紹互補產品。', 'zh-CN': '向现有客户介绍互补产品。',
      'ja': '既存顧客に補完製品を紹介します。', 'ko': '기존 고객에게 보완 제품을 소개합니다.',
      'th': 'แนะนำผลิตภัณฑ์เสริมให้ลูกค้าเดิม', 'vi': 'Giới thiệu sản phẩm bổ sung cho khách hàng hiện tại.',
      'ms': 'Perkenalkan produk pelengkap kepada pelanggan sedia ada.', 'id': 'Perkenalkan produk pelengkap ke pelanggan yang ada.',
    },
    difficulty: 'intermediate',
    category: 'closing',
    aiRole: 'Existing customer using one product line',
    aiPersonality: 'Open to suggestions but budget-conscious.',
    expectedSkills: ['needs bridging', 'synergy selling', 'bundle value'],
    maxTurns: 8,
  },
  {
    id: 'negotiation_discount',
    name: {
      'en': 'Discount Negotiation', 'zh-TW': '折扣談判', 'zh-CN': '折扣谈判',
      'ja': '値引き交渉', 'ko': '할인 협상',
      'th': 'เจรจาส่วนลด', 'vi': 'Đàm phán giảm giá', 'ms': 'Rundingan Diskaun', 'id': 'Negosiasi Diskon',
    },
    description: {
      'en': 'Handle aggressive discount requests.', 'zh-TW': '處理積極的折扣要求。', 'zh-CN': '处理积极的折扣要求。',
      'ja': '積極的な値引き要求に対応します。', 'ko': '적극적인 할인 요청을 처리합니다.',
      'th': 'จัดการคำขอส่วนลดอย่างจริงจัง', 'vi': 'Xử lý yêu cầu giảm giá mạnh.',
      'ms': 'Tangani permintaan diskaun yang agresif.', 'id': 'Tangani permintaan diskon agresif.',
    },
    difficulty: 'advanced',
    category: 'closing',
    aiRole: 'Procurement manager seeking maximum discount',
    aiPersonality: 'Tough but fair negotiator. Respects competence.',
    expectedSkills: ['value protection', 'trade-off negotiation', 'creative packaging'],
    maxTurns: 10,
  },
  {
    id: 'negotiation_terms',
    name: {
      'en': 'Terms Negotiation', 'zh-TW': '條件談判', 'zh-CN': '条件谈判',
      'ja': '条件交渉', 'ko': '조건 협상',
      'th': 'เจรจาเงื่อนไข', 'vi': 'Đàm phán điều khoản', 'ms': 'Rundingan Syarat', 'id': 'Negosiasi Ketentuan',
    },
    description: {
      'en': 'Negotiate payment terms and contract conditions.', 'zh-TW': '協商付款條件和合約內容。', 'zh-CN': '协商付款条件和合同内容。',
      'ja': '支払い条件と契約条件を交渉します。', 'ko': '지불 조건과 계약 조건을 협상합니다.',
      'th': 'เจรจาเงื่อนไขการชำระเงินและสัญญา', 'vi': 'Đàm phán điều khoản thanh toán và hợp đồng.',
      'ms': 'Rundingkan syarat pembayaran dan kontrak.', 'id': 'Negosiasikan syarat pembayaran dan kontrak.',
    },
    difficulty: 'advanced',
    category: 'closing',
    aiRole: 'Finance director discussing payment terms',
    aiPersonality: 'Business-driven, wants net 60 terms.',
    expectedSkills: ['win-win framing', 'term flexibility', 'relationship preservation'],
    maxTurns: 8,
  },
  {
    id: 'gate_keeper',
    name: {
      'en': 'Getting Past the Gatekeeper', 'zh-TW': '突破守門人', 'zh-CN': '突破看门人',
      'ja': 'ゲートキーパー突破', 'ko': '게이트키퍼 돌파',
      'th': 'ผ่านผู้เฝ้าประตู', 'vi': 'Vượt qua thư ký', 'ms': 'Melepasi Penjaga Pintu', 'id': 'Melewati Penjaga Gerbang',
    },
    description: {
      'en': 'Get past an assistant to reach the decision maker.', 'zh-TW': '突破助理接觸到決策者。', 'zh-CN': '突破助理接触到决策者。',
      'ja': 'アシスタントを突破して意思決定者に到達します。', 'ko': '비서를 통과하여 의사결정자에게 도달합니다.',
      'th': 'ผ่านผู้ช่วยไปถึงผู้ตัดสินใจ', 'vi': 'Vượt qua trợ lý để tiếp cận người ra quyết định.',
      'ms': 'Melepasi pembantu untuk mencapai pembuat keputusan.', 'id': 'Melewati asisten untuk mencapai pengambil keputusan.',
    },
    difficulty: 'intermediate',
    category: 'discovery',
    aiRole: 'Executive assistant protecting boss\'s calendar',
    aiPersonality: 'Professional, protective, but not unfriendly.',
    expectedSkills: ['rapport with gatekeepers', 'value teaser', 'persistence'],
    maxTurns: 6,
  },
  {
    id: 'executive_pitch',
    name: {
      'en': 'Executive Pitch', 'zh-TW': '高管簡報', 'zh-CN': '高管简报',
      'ja': 'エグゼクティブピッチ', 'ko': '임원 피칭',
      'th': 'นำเสนอต่อผู้บริหาร', 'vi': 'Thuyết trình cấp lãnh đạo', 'ms': 'Pembentangan Eksekutif', 'id': 'Pitch Eksekutif',
    },
    description: {
      'en': 'Pitch to a C-level exec with limited time.', 'zh-TW': '向時間有限的高階主管簡報。', 'zh-CN': '向时间有限的高管简报。',
      'ja': '限られた時間でCレベルの役員にピッチします。', 'ko': '제한된 시간으로 C레벨 임원에게 피칭합니다.',
      'th': 'นำเสนอต่อผู้บริหารระดับสูงที่มีเวลาจำกัด', 'vi': 'Thuyết trình cho lãnh đạo cấp cao trong thời gian hạn chế.',
      'ms': 'Pembentangan kepada eksekutif C-level dengan masa terhad.', 'id': 'Pitch ke eksekutif C-level dengan waktu terbatas.',
    },
    difficulty: 'advanced',
    category: 'presentation',
    aiRole: 'CEO with 10 minutes between meetings',
    aiPersonality: 'Strategic thinker, only cares about big picture and ROI.',
    expectedSkills: ['elevator pitch', 'strategic framing', 'executive presence'],
    maxTurns: 6,
  },

  // --- Networking (2 scenarios) ---
  {
    id: 'networking_event',
    name: {
      'en': 'Networking Event', 'zh-TW': '社交活動', 'zh-CN': '社交活动',
      'ja': 'ネットワーキングイベント', 'ko': '네트워킹 이벤트',
      'th': 'งานเครือข่าย', 'vi': 'Sự kiện kết nối', 'ms': 'Acara Jaringan', 'id': 'Acara Networking',
    },
    description: {
      'en': 'Make a meaningful connection at a business event.', 'zh-TW': '在商務活動中建立有意義的連結。', 'zh-CN': '在商务活动中建立有意义的连接。',
      'ja': 'ビジネスイベントで有意義なつながりを作ります。', 'ko': '비즈니스 행사에서 의미 있는 연결을 만듭니다.',
      'th': 'สร้างความสัมพันธ์ที่มีความหมายในงานธุรกิจ', 'vi': 'Tạo kết nối có ý nghĩa tại sự kiện kinh doanh.',
      'ms': 'Bina hubungan bermakna di acara perniagaan.', 'id': 'Bangun koneksi bermakna di acara bisnis.',
    },
    difficulty: 'beginner',
    category: 'networking',
    aiRole: 'Fellow attendee at a business conference',
    aiPersonality: 'Friendly, open to conversation, hates hard sells.',
    expectedSkills: ['natural conversation', 'genuine interest', 'memorable introduction'],
    maxTurns: 8,
  },
  {
    id: 'linkedin_outreach',
    name: {
      'en': 'LinkedIn Outreach', 'zh-TW': 'LinkedIn 開發', 'zh-CN': 'LinkedIn 开发',
      'ja': 'LinkedIn アウトリーチ', 'ko': 'LinkedIn 아웃리치',
      'th': 'การติดต่อผ่าน LinkedIn', 'vi': 'Tiếp cận qua LinkedIn', 'ms': 'Jangkauan LinkedIn', 'id': 'Outreach LinkedIn',
    },
    description: {
      'en': 'Engage a prospect through LinkedIn messaging.', 'zh-TW': '透過 LinkedIn 訊息接觸潛在客戶。', 'zh-CN': '通过 LinkedIn 消息接触潜在客户。',
      'ja': 'LinkedInメッセージで見込み客にアプローチします。', 'ko': 'LinkedIn 메시지로 잠재 고객에게 접근합니다.',
      'th': 'ติดต่อลูกค้าผ่านข้อความ LinkedIn', 'vi': 'Tiếp cận khách hàng qua tin nhắn LinkedIn.',
      'ms': 'Libatkan prospek melalui pemesejan LinkedIn.', 'id': 'Libatkan prospek melalui pesan LinkedIn.',
    },
    difficulty: 'beginner',
    category: 'networking',
    aiRole: 'Professional who received a LinkedIn connection request',
    aiPersonality: 'Skeptical of spam but responds to genuine, personalized messages.',
    expectedSkills: ['personalization', 'social selling', 'connection-before-pitch'],
    maxTurns: 6,
  },
]

export function getScenarioById(id: CoachScenario): CoachScenarioConfig | undefined {
  return COACH_SCENARIOS.find((s) => s.id === id)
}

export function getScenariosByCategory(category: string): CoachScenarioConfig[] {
  return COACH_SCENARIOS.filter((s) => s.category === category)
}

export function getScenariosByDifficulty(difficulty: string): CoachScenarioConfig[] {
  return COACH_SCENARIOS.filter((s) => s.difficulty === difficulty)
}
